### PR TITLE
Updated for FlatPress 1.3 / Smarty 4

### PR DESCRIPTION
**Pull request by azett**
With the upcoming FlatPress 1.3 updating Smarty to v4, the Smarty function names have changed. I felt free to update the Tag plugin to continue working, and to call the new version "2.6".
Would be great to have this pulled and created an "official" release with.

All the best,
Arvid

### CODE REVIEW

**Comment by ebal** [comment]
Hi @azett 

Do you know if this solves https://github.com/ebal/flatpress_tag_plugin/issues/2  (I guess it does) ?

**Comment by azett** [comment]
It does indeed :) 
@Fraenkiman reported the issue [on the support forum](https://forum.flatpress.org/viewtopic.php?t=462), this caused my fix. Didn't notice he reported it here as well.

All the best,
Arvid

**Comment by azett** [comment]
Update: You could additionally determine the available Smarty version in order to have the new plugin version running in FlatPress <=1.2 _and_ >=1.3 :)
https://wiki.flatpress.org/doc:tips:smarty2to4#keep_your_plugin_backward_compatible

**Comment by ebal** [comment]
@azett  I am trying to test the tag-plugin (smarty update) with the latest git flatpress code in a clean (freshly installed VM) and getting a 404 Not Found with 

```bash
localhost/flatpress/index.php/2022/11/05/welcome-to-flatpress
```

I can install your tag-plugin branch but even then, when creating a new post, does not seem to work (404 Not Found)  ... I (almost) sure that I can merge it and tag it with a new version but it would be great to test it before merging.

any ideas on that ?

ps. perhaps it is not the best place here to discuss it but then again ...

**Comment by azett** [comment]
Do you have mod_rewrite enabled? If not, try to deactivate the PrettyURLs plugin and call localhost/flatpress again - does it work now?

**Comment by ebal** [comment]
closes https://github.com/ebal/flatpress_tag_plugin/issues/2

**Pull request merged**
